apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
    component: nsqlookupd-broker
spec:
  type: NodePort
  ports:
  - port: 4160
    name: tcp
    targetPort: 4160
    protocol: TCP
    nodePort: 30160
  - port: 4161
    name: http
    targetPort: 4161
    protocol: TCP
    nodePort: 30161
  selector:
    app: nsqlookupd
    component: nsqlookupd-broker
---
